### ISSUE TITLE
Only enables ASPM L1, not L0s

### ISSUE THREAD

**Issue by jepperc** [KastB/r8169#1]
And skylake does not go into PC6 when L0s is not enabled... any idea how to fix?

>  LnkCtl: ASPM L1 Enabled; RCB 64 bytes Disabled- CommClk+

**Comment by KastB** [comment]
Hi
have you tried the "enable_aspm" script, that can be found  on "http://linuxwireless.org/en/users/Documentation/ASPM/" ?

**Comment by jepperc** [comment]
Yes, doesnt change anything. Did it manually with setpci before.
For some reason, the 8168 driver enables both L0s and L1, and this 8169
only enables L1. But I can't se anything in the source code that makes this
happen?

(the reason i'm not using the 8168 is that the receive speed is unstable
and only 30-90 mbit).

**Comment by KastB** [comment]
The r8168 was unstable for me as well.
The initialization seems to pretty similar. Nevertheless there are some additional parts in the r8168 that are not implemented in the r8169, which could be found by searching for occurances of 'aspm' that are not within 'rtl8168_hw_config'.
You could try to find the relevant one by commenting them out one after the other until L0s doesn't work with the r8168 as well and reimplement that part in r8169...

**Comment by jepperc** [comment]
Thanks! Will have time to look at it this weekend :)

**Comment by jepperc** [comment]
So, apparantly I have the 8168h card, where aspm is not enabled after ephy access.
I added that, and now I got aspm working, but network speed is back to sucking like the r8168 driver. 
So annoyed with this, and it's too late for me to return the mobo to get one with an intel nic :(

**Comment by jepperc** [comment]
Fixed it! Found that some adapters had a RTL_W32(MISC, RTL_R32(MISC) | FORCE_CLK); after enabling aspm, and now performance is good, but aspm still works. Will make a PR

**Comment by KastB** [comment]
Thanks for that PR.
Is your issue solved then?

**Comment by jepperc** [comment]
Yes, seems to work perfectly
