### ISSUE TITLE
PSA: aspm is being re-enabled in 4.19

### ISSUE THREAD

**Issue by mirh** [KastB/r8169#6]
https://patchwork.kernel.org/patch/10479457/ and following

**Comment by mirh** [comment]
A ton of other patches also landed following that 
https://github.com/torvalds/linux/commits/master/drivers/net/ethernet/realtek/r8169.c

**Comment by mirh** [comment]
Duh, back we are https://www.spinics.net/lists/netdev/msg562686.html

**Comment by TwoLeaves** [comment]
Patches allowing the toggling of ASPM via sysfs, due in 5.5: https://patchwork.kernel.org/project/linux-pci/list/?series=183179

**Comment by KastB** [comment]
Hi,
does this work for you?
For my system it isn't automatically enabled.

**Comment by mirh** [comment]
https://github.com/torvalds/linux/blob/v5.6/drivers/net/ethernet/realtek/r8169_main.c#L5474
Because it isn't (and it might never be, given the just immense number of boards, chips, revisions and firmwares). 
You should be able to manually enable it [through sysfs](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-bus-pci) though, since 5.5. 

Or at least this is the case if your bios isn't FUBAR.. See https://github.com/torvalds/linux/commit/62b1b3b3b6d3ef309b1024aea95265c01929933c.
